// `.env.ts` is generated by the `npm run env` command
import env from "@env/.env";

export const environment = {
	production: false,
	version: env.npm_package_version,
	serverUrl: "http://backend.devel.sinamecc.go.cr/api",
	carbonUrl: "http://mccr.devel.sinamecc.go.cr/api",
	defaultLanguage: "en-US",
	supportedLanguages: ["en-US", "es-CR"]
};
