// `.env.ts` is generated by the `npm run env` command
import env from '@env/.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://dev-backend.sinamecc.go.cr',
  mediaUrl: 'http://dev-backend.sinamecc.go.cr',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    // 'fr-FR'
    'es-CR'
  ]
};
