// `.env.ts` is generated by the `npm run env` command
import env from "@env/.env";

export const environment = {
	production: false,
	version: env.npm_package_version,
	defaultLanguage: "en-US",
	serverUrl: "/api",
	carbonUrl: "/carbonmarket",
	supportedLanguages: ["en-US", "es-CR"]
};
