// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://stage.sinamecc-minae.com:8000/api',
  mediaUrl: 'http://stage.sinamecc-minae.com',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    // 'fr-FR'
    'es-CR'
  ]
};
