name: Deploy on ECS
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (development, production)'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - production

jobs:
  env-vars:
    name: 'Set Environment Variables'
    runs-on: ubuntu-latest
    steps:
      - name: Set Stage
        run: |
          echo "Discovering the environment stage:"
          if [[ ${{ inputs.environment }} == 'production' ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [[ ${{ inputs.environment }} == 'development' ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "Invalid environment stage"
            exit 1
          fi
  register-images:
    name: 'Register Images'
    needs: env-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute script
        run: |
          echo "Registering images for $ENVIRONMENT"
